name: 3d-contrib

on:
  schedule: # 03:00 hora de Monterrey == 09:00 UTC
    - cron: "0 9 * * *"
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: genera el horizonte 3D de contribuciones
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: commit y push si hay cambios
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A profile-3d-contrib
          if git commit -m "chore: actualiza el horizonte 3d de contribuciones"; then
            git push
          fi
